[0m00:09:26.369219 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012882689B20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001287E8515E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001287EE2B410>]}


============================== 00:09:26.372220 | 06cbe898-b89c-41dc-b3c2-566d6af21b29 ==============================
[0m00:09:26.372220 [info ] [MainThread]: Running with dbt=1.8.1
[0m00:09:26.373220 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\PC\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m00:10:41.477566 [debug] [MainThread]: Starter project path: C:\Users\PC\Desktop\pythonETL\dbt_venv\Lib\site-packages\dbt\include\starter_project
[0m00:10:41.492565 [info ] [MainThread]: 
Your new dbt project "dbt_ilab" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:10:41.493565 [info ] [MainThread]: Setting up your profile.
[0m00:11:08.503485 [info ] [MainThread]: Profile dbt_ilab written to C:\Users\PC\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m00:11:08.504482 [debug] [MainThread]: Command `dbt init` succeeded at 00:11:08.504482 after 102.25 seconds
[0m00:11:08.505483 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012882720530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012882689B20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001288311A9C0>]}
[0m00:11:08.505483 [debug] [MainThread]: Flushing usage events
[0m00:13:38.130761 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B1BDFFEF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B1BDFD8E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B1BDFD700>]}


============================== 00:13:38.134761 | de5dff76-e53d-4d13-8588-e23f81672c2a ==============================
[0m00:13:38.134761 [info ] [MainThread]: Running with dbt=1.8.1
[0m00:13:38.134761 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\PC\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m00:13:38.135762 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\PC\Desktop\pythonETL\dbt-airflow-dag\dags\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:13:38.137763 [debug] [MainThread]: Command `dbt run` failed at 00:13:38.136761 after 0.12 seconds
[0m00:13:38.137763 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B1BD1A9C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B1AE08FE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B1BE85C70>]}
[0m00:13:38.137763 [debug] [MainThread]: Flushing usage events
